# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Programming\PyQt5\Auto_Shutdown_Manager\Auto_Shutdown_Manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import datetime
import os
import time
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Auto_Shutdown_Manager(object):
    def setupUi(self, Auto_Shutdown_Manager):
        Auto_Shutdown_Manager.setObjectName("Auto_Shutdown_Manager")
        Auto_Shutdown_Manager.resize(400, 300)

        self.Text_Title = QtWidgets.QLabel(Auto_Shutdown_Manager)
        self.Text_Title.setGeometry(QtCore.QRect(10, 10, 381, 41))

        font = QtGui.QFont()
        font.setFamily("메이플스토리 OTF")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Text_Title.setFont(font)
        self.Text_Title.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Text_Title.setStyleSheet("background-color: rgb(80, 250, 15);\n"
"border:2px solid;\n"
"border-color: rgb(195, 195, 195);\n"
"border-top-left-radius: 50px;\n"
"border-bottom-right-radius: 50px;color: rgb(8, 8, 8);")
        self.Text_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Text_Title.setObjectName("Text_Title")
        self.Button_Close = QtWidgets.QPushButton(Auto_Shutdown_Manager)
        self.Button_Close.setGeometry(QtCore.QRect(10, 252, 381, 41))

        font = QtGui.QFont()
        font.setFamily("메이플스토리 OTF")
        font.setPointSize(16)
        self.Button_Close.setFont(font)
        self.Button_Close.setObjectName("Button_Close")
        self.Button_Cancel = QtWidgets.QPushButton(Auto_Shutdown_Manager)
        self.Button_Cancel.setGeometry(QtCore.QRect(210, 70, 151, 41))

        font = QtGui.QFont()
        font.setFamily("메이플스토리 OTF")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.Button_Cancel.setFont(font)
        self.Button_Cancel.setStyleSheet("background-color:rgb(200,200,255);\n"
"border:1px solid;\n"
"border-color: rgb(10, 150, 255);\n"
"border-top-left-radius: 7px;\n"
"border-top-right-radius: 7px;\n"
"border-bottom-left-radius: 7px;\n"
"border-bottom-right-radius: 7px;")
        self.Button_Cancel.setObjectName("Button_Cancel")
        self.Button_H = QtWidgets.QPushButton(Auto_Shutdown_Manager)
        self.Button_H.setGeometry(QtCore.QRect(210, 120, 151, 31))

        font = QtGui.QFont()
        font.setFamily("메이플스토리 OTF")
        font.setPointSize(12)
        self.Button_H.setFont(font)
        self.Button_H.setStyleSheet("background-color:rgb(255,210,0);\n"
"border:1px solid;\n"
"border-color: rgb(0, 0, 0);\n"
"border-top-left-radius: 7px;\n"
"border-top-right-radius: 7px;\n"
"border-bottom-left-radius: 7px;\n"
"border-bottom-right-radius: 7px;")
        self.Button_H.setObjectName("Button_H")
        self.Input_H = QtWidgets.QSpinBox(Auto_Shutdown_Manager)
        self.Input_H.setGeometry(QtCore.QRect(40, 120, 121, 31))

        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.Input_H.setFont(font)
        self.Input_H.setStyleSheet("border:1px solid;\n"
"border-color: rgb(0, 0, 0);\n"
"border-top-left-radius: 5px;\n"
"border-top-right-radius: 5px;\n"
"border-bottom-left-radius: 5px;\n"
"border-bottom-right-radius: 5px;")
        self.Input_H.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.Input_H.setAlignment(QtCore.Qt.AlignCenter)
        self.Input_H.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.Input_H.setMaximum(24)
        self.Input_H.setObjectName("Input_H")
        self.Input_M = QtWidgets.QSpinBox(Auto_Shutdown_Manager)
        self.Input_M.setGeometry(QtCore.QRect(40, 160, 121, 31))

        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.Input_M.setFont(font)
        self.Input_M.setStyleSheet("border:1px solid;\n"
"border-color: rgb(0, 0, 0);\n"
"border-top-left-radius: 5px;\n"
"border-top-right-radius: 5px;\n"
"border-bottom-left-radius: 5px;\n"
"border-bottom-right-radius: 5px;")
        self.Input_M.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.Input_M.setAlignment(QtCore.Qt.AlignCenter)
        self.Input_M.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.Input_M.setMaximum(1440)
        self.Input_M.setObjectName("Input_M")
        self.Button_M = QtWidgets.QPushButton(Auto_Shutdown_Manager)
        self.Button_M.setGeometry(QtCore.QRect(210, 160, 151, 31))

        font = QtGui.QFont()
        font.setFamily("메이플스토리 OTF")
        font.setPointSize(12)
        self.Button_M.setFont(font)
        self.Button_M.setStyleSheet("background-color:rgb(255,210,0);\n"
"border:1px solid;\n"
"border-color: rgb(0, 0, 0);\n"
"border-top-left-radius: 7px;\n"
"border-top-right-radius: 7px;\n"
"border-bottom-left-radius: 7px;\n"
"border-bottom-right-radius: 7px;")
        self.Button_M.setObjectName("Button_M")
        self.Input_S = QtWidgets.QSpinBox(Auto_Shutdown_Manager)
        self.Input_S.setGeometry(QtCore.QRect(40, 200, 121, 31))

        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.Input_S.setFont(font)
        self.Input_S.setStyleSheet("border:1px solid;\n"
"border-color: rgb(0, 0, 0);\n"
"border-top-left-radius: 5px;\n"
"border-top-right-radius: 5px;\n"
"border-bottom-left-radius: 5px;\n"
"border-bottom-right-radius: 5px;")
        self.Input_S.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.Input_S.setAlignment(QtCore.Qt.AlignCenter)
        self.Input_S.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.Input_S.setMaximum(86400)
        self.Input_S.setObjectName("Input_S")
        self.Button_S = QtWidgets.QPushButton(Auto_Shutdown_Manager)
        self.Button_S.setGeometry(QtCore.QRect(210, 200, 151, 31))

        font = QtGui.QFont()
        font.setFamily("메이플스토리 OTF")
        font.setPointSize(12)
        self.Button_S.setFont(font)
        self.Button_S.setStyleSheet("background-color:rgb(255,210,0);\n"
"border:1px solid;\n"
"border-color: rgb(0, 0, 0);\n"
"border-top-left-radius: 7px;\n"
"border-top-right-radius: 7px;\n"
"border-bottom-left-radius: 7px;\n"
"border-bottom-right-radius: 7px;")
        self.Button_S.setObjectName("Button_S")
        self.label_2 = QtWidgets.QLabel(Auto_Shutdown_Manager)
        self.label_2.setGeometry(QtCore.QRect(110, 120, 21, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Auto_Shutdown_Manager)
        self.label_3.setGeometry(QtCore.QRect(110, 160, 21, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Auto_Shutdown_Manager)
        self.label_4.setGeometry(QtCore.QRect(110, 200, 21, 31))
        self.label_4.setObjectName("label_4")
        self.Text_Time = QtWidgets.QTextBrowser(Auto_Shutdown_Manager)
        self.Text_Time.setGeometry(QtCore.QRect(40, 70, 121, 41))
        self.Text_Time.setStyleSheet("border:1px solid;\n"
"border-color: rgb(10, 150, 255);\n"
"border-top-left-radius: 5px;\n"
"border-top-right-radius: 5px;\n"
"border-bottom-left-radius: 5px;\n"
"border-bottom-right-radius: 5px;")
        self.Text_Time.setObjectName("Text_Time")
        self.frame = QtWidgets.QFrame(Auto_Shutdown_Manager)
        self.frame.setGeometry(QtCore.QRect(10, 60, 381, 181))
        self.frame.setStyleSheet("background-color: rgb(210, 210, 210);\n"
"border:2px solid;\n"
"border-color: rgb(153, 217, 234);\n"
"border-top-left-radius: 15px;\n"
"border-top-right-radius: 15px;\n"
"border-bottom-left-radius: 15px;\n"
"border-bottom-right-radius: 15px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.Text_Title.raise_()
        self.Button_Close.raise_()
        self.Button_Cancel.raise_()
        self.Button_H.raise_()
        self.Input_H.raise_()
        self.Input_M.raise_()
        self.Button_M.raise_()
        self.Input_S.raise_()
        self.Button_S.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.Text_Time.raise_()

        self.retranslateUi(Auto_Shutdown_Manager)
        QtCore.QMetaObject.connectSlotsByName(Auto_Shutdown_Manager)

    def retranslateUi(self, Auto_Shutdown_Manager):
        _translate = QtCore.QCoreApplication.translate
        Auto_Shutdown_Manager.setWindowTitle(_translate("Auto_Shutdown_Manager", "Auto Shutdown Manager [ baebine@naver.com ]"))
        self.Text_Title.setText(_translate("Auto_Shutdown_Manager", "컴퓨터 예약 종료"))
        self.Button_Close.setText(_translate("Auto_Shutdown_Manager", "창 닫기"))
        self.Button_Cancel.setText(_translate("Auto_Shutdown_Manager", "예약 취소하기"))
        self.Button_H.setText(_translate("Auto_Shutdown_Manager", "종료 예약하기"))
        self.Button_M.setText(_translate("Auto_Shutdown_Manager", "종료 예약하기"))
        self.Button_S.setText(_translate("Auto_Shutdown_Manager", "종료 예약하기"))

        self.Button_Cancel.clicked.connect(self.clickMethod_Cancel)
        self.Button_Close.clicked.connect(self.clickMethod_Close)
        self.Button_H.clicked.connect(self.clickMethod_H)
        self.Button_M.clicked.connect(self.clickMethod_M)
        self.Button_S.clicked.connect(self.clickMethod_S)

        self.label_2.setText(_translate("Auto_Shutdown_Manager", "(시)"))
        self.label_3.setText(_translate("Auto_Shutdown_Manager", "(분)"))
        self.label_4.setText(_translate("Auto_Shutdown_Manager", "(초)"))

        now=datetime.datetime.now()

        self.Text_Time.setHtml(_translate("Auto_Shutdown_Manager", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">시작 시간</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">%02d:%02d:%02d</span></p></body></html>" %(now.hour,now.minute,now.second)))


    def clickMethod_Cancel(self):
        os.system("shutdown -a")

    def clickMethod_Close(self):
        sys.exit(app.exec_())

    def clickMethod_H(self):
        if int(self.Input_H.text()) >= 1:
            os.system("shutdown -s -t %s" % str(int(self.Input_H.text())*3600))

    def clickMethod_M(self):
        if int(self.Input_M.text()) >= 5:
            os.system("shutdown -s -t %s" % str(int(self.Input_M.text())*60))

    def clickMethod_S(self):
        if int(self.Input_S.text()) >= 300:
            os.system("shutdown -s -t %s" % str(int(self.Input_S.text())))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Auto_Shutdown_Manager = QtWidgets.QDialog()
    ui = Ui_Auto_Shutdown_Manager()
    ui.setupUi(Auto_Shutdown_Manager)
    Auto_Shutdown_Manager.show()
    sys.exit(app.exec_())
